GET http://localhost:3000

###
POST http://localhost:8080/assets
Content-Type: application/json

{
  "symbol": "GOOG",
  "name": "Google"
}

###
GET http://localhost:8080/wallets
Content-Type: application/json

###
POST http://localhost:8080/wallets


###
GET http://localhost:8080/wallets/1f8fa8ed-0598-48d6-9933-d83aef8c1463/assets

###
GET http://localhost:8080/wallets/52a78cc4-a523-42bc-b96e-59599350a8b2/assets

###
# Outra opção: POST http://localhost:3000/wallets/wallet1/orders
POST http://localhost:8080/wallets/52a78cc4-a523-42bc-b96e-59599350a8b2/orders
Content-Type: application/json

// se tivesse autenticado, não precisaria do wallet_id
{
  "assetId": "AMD",
  "shares": 1,
  "price": 167.69,
  "type": "BUY"
}

###
POST http://localhost:8080/wallets/1f8fa8ed-0598-48d6-9933-d83aef8c1463/orders
Content-Type: application/json

// se tivesse autenticado, não precisaria do wallet_id
{
  "assetId": "AMD",
  "shares": 1,
  "price": 167.69,
  "type": "SELL"
}

###
GET http://localhost:8080/wallets/1f8fa8ed-0598-48d6-9933-d83aef8c1463/orders

###
GET http://localhost:8080/wallets/52a78cc4-a523-42bc-b96e-59599350a8b2/orders


###
GET http://localhost:8080/assets/PETR4/daily

###
GET https://localhost:8080/assets/IBM/series

###
GET http://localhost:8080/assets/AMD/series/events

###
GET https://localhost:8080/assets/AAPL/candle


###
GET https://localhost:8080/assets/AAPL/candle/events

###
GET http://localhost:8080/assets/in?symbols=AMD,AMZN,AAPL,IBM,GOOG,ASDASD,

###
GET http://localhost:8080/assets?notIn=JNJ,WMT&page=1&size=10

###
GET https://localhost:8080/assets?notIn=NARUTO&size=100
